version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://app:password@postgres:5432/appdb?schema=public
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: change_me
    depends_on:
      - postgres

volumes:
  pgdata:
